[package]

name = "tenderdash-abci"
edition = "2024"
license = "Apache-2.0"
readme = "README.md"
categories = ["cryptography::cryptocurrencies", "network-programming"]
keywords = ["abci", "blockchain", "bft", "consensus", "tendermint", "dash"]
repository = "https://github.com/dashpay/rs-tenderdash-abci/tree/main/abci"
documentation = "https://dashpay.github.io/rs-tenderdash-abci/tenderdash_abci/"

description = """tenderdash-abci provides a simple framework with which to build\
low-level applications on top of Tenderdash."""

rust-version.workspace = true
version.workspace = true

[features]
# By default, include the server feature together with both tcp and unix transports.
default = ["server", "docker-tests", "crypto", "tcp", "unix", "tracing-span"]
# docker-tests includes integration tests that require docker to be available
docker-tests = ["server"]
# Enable server support; this is most likely what you want (plus `tcp` and/or `unix`)
server = [
    "tracing-subscriber/fmt",
    "tenderdash-proto/server",
    "dep:tokio",
    "dep:tokio-util",
    "dep:futures",
    "std",
]
# DEPRECATED; use `server` instead
grpc = ["server"]

# Disable no_std support
std = ["tenderdash-proto/std"]

# Include crypto features, like signature verification
crypto = ["dep:lhash"]

# Include server TCP support
tcp = ["server"]

# Include server unix socket support
unix = ["server"]

# Include `tracing` crate spans
tracing-span = ["dep:uuid"]

# Include `serde` support
serde = ["tenderdash-proto/serde", "dep:serde_json"]

[[example]]
name = "echo_socket"
required-features = ["server"]

[dependencies]
uuid = { version = "1.8.0", features = ["v4", "fast-rng"], optional = true }
tenderdash-proto = { path = "../proto", default-features = false }
bytes = { version = "1.6.0" }
tracing = { version = "0.1.40", default-features = false }
tracing-subscriber = { version = "0.3.18", optional = true, default-features = false, features = [
    "ansi",
    "env-filter",
] }
serde_json = { version = "1.0.128", optional = true }
thiserror = { version = "2.0.3" }
url = { version = "2.5.0" }
semver = { version = "1.0.22" }
lhash = { version = "1.1.0", features = ["sha256"], optional = true }
hex = { version = "0.4.3" }
tokio-util = { version = "0.7.12", features = [
    "net",
    "codec",
], default-features = false, optional = true }
tokio = { version = "1.40", features = [
    "net",
    "io-util",
    "rt-multi-thread",
    "sync",
    "macros",
], default-features = false, optional = true }
futures = { version = "0.3.30", optional = true }

[dev-dependencies]
anyhow = { version = "1.0.82" }
bincode = { version = "3.0.0" }
blake2 = { version = "0.10.6" }
bollard = { version = "0.19" }
futures = { version = "0.3.30" }
tokio = { version = "1.40", features = ["macros", "signal", "time", "io-std"] }
hex = { version = "0.4.3" }
lazy_static = { version = "1.4.0" }
# Note: pollster is not safe outside of tests, we had issues with it in the past
pollster = { version = "0.4.0" }
