unstable_features = true

# comments
comment_width = 95
normalize_comments = true
wrap_comments = true

# imports
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
reorder_imports = true

# strings
format_strings = false
max_width = 95
match_block_trailing_comma = true

trailing_comma = "Vertical"
trailing_semicolon = true
