[workspace]

members = ["abci", "tools/proto-compiler", "proto"]

exclude = ["tools/no-std-check"]

[profile.release.package.tendermint-light-client-js]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
