[package]
name = "tenderdash-proto-compiler"
version = "0.1.0"
authors = ["Informal Systems <hello@informal.systems>"]
edition = "2021"
description = "Internal tool to download and build tenderdash protobuf definitions; used by proto/build.rs"
publish = false

[lib]

[dependencies]
walkdir = { version = "2.3" }
prost-build = { version = "0.11" }
tempfile = { version = "3.2.0" }
regex = { "version" = "1.7.1" }
reqwest = { "version" = "0.11.16", features = ["blocking"] }
zip = { version = "0.6.4", default-features = false, features = ["deflate"] }
fs_extra = { version = "1.3.0" }
# we need to build vendored openssl to avoid issues on Alpine
openssl = { version = "0.10", features = ["vendored"] }
