[package]
name = "tenderdash-proto-compiler"
version = "0.1.0"
authors = ["Informal Systems <hello@informal.systems>"]
edition = "2021"
publish = false

[lib]

[dependencies]
walkdir = { version = "2.3" }
prost-build = { version = "0.11" }
git2 = { version = "0.16" }
tempfile = { version = "3.2.0" }
subtle-encoding = { version = "0.5" }
regex = { "version" = "1.7.1" }
