---
name: "Dependencies"
description: "Install dependencies"
runs:
  using: composite
  steps:
    - uses: actions-rs/toolchain@v1
      name: Install Rust toolchain
      with:
        toolchain: stable
        override: true
    - name: Install protoc
      id: deps-protoc
      shell: bash
      run: |
        curl -Lo /tmp/protoc.zip \
          https://github.com/protocolbuffers/protobuf/releases/download/v22.0/protoc-22.0-linux-x86_64.zip
        unzip /tmp/protoc.zip -d ${HOME}/.local
        echo "PROTOC=${HOME}/.local/bin/protoc" >> $GITHUB_ENV
        export PATH="${PATH}:${HOME}/.local/bin"
    - name: Compile Protobuf definitions
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release -p tenderdash-proto
