---
name: "Dependencies"
description: "Install dependencies"
inputs:
  toolchain:
    description: Rust toolchain to use, stable / nightly / beta
    default: stable
runs:
  using: composite
  steps:
    - uses: dtolnay/rust-toolchain@master
      name: Install Rust toolchain
      with:
        toolchain: ${{ inputs.toolchain }}

    - name: Install protoc
      id: deps-protoc
      shell: bash
      run: sudo apt-get update && sudo apt-get install --yes protobuf-compiler

    - name: Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        cache-directories: |
          proto/src/prost
    - name: Compile Protobuf definitions
      shell: bash
      run: cargo build -p tenderdash-proto
