---
name: "Dependencies"
description: "Install dependencies"
inputs:
  toolchain:
    description: Rust toolchain to use, stable / nightly / beta
    default: stable
runs:
  using: composite
  steps:
    - uses: actions-rs/toolchain@v1
      name: Install Rust toolchain
      with:
        toolchain: ${{ inputs.toolchain }}
        profile: minimal
        override: true
    - name: Install protoc
      id: deps-protoc
      shell: bash
      run: |
        curl -Lo /tmp/protoc.zip \
          https://github.com/protocolbuffers/protobuf/releases/download/v22.0/protoc-22.0-linux-x86_64.zip
        unzip /tmp/protoc.zip -d ${HOME}/.local
        echo "PROTOC=${HOME}/.local/bin/protoc" >> $GITHUB_ENV
        export PATH="${PATH}:${HOME}/.local/bin"
    - name: Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        cache-directories: |
          proto/src/prost
    - name: Compile Protobuf definitions
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release -p tenderdash-proto
