---
name: Github Pages

on:
  push:
    branches:
      - master
      - "build/docs-website" # TODO remove after it's merged
jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master'"

  gh-pages:
    # environment:
    #   name: github-pages
    #   url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/deps

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Generate documentation
        shell: bash
        env:
          RUSTDOCFLAGS: "--cfg docsrs"
        run: cargo doc --no-deps --all-features  --workspace --exclude tenderdash-proto-compiler

      - name: Generate index page
        shell: bash
        run: |
          cat >  target/doc/index.html << EOF
          <html><head><meta http-equiv="refresh" content="0; url=tenderdash_abci/" /></head>
          <body><a href="tenderdash_abci/">Click here</a></body>
          </html>
          EOF

      - name: Upload docs
        uses: actions/upload-pages-artifact@v1
        with:
          path: "target/doc"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
