name: no_std check
on:
  pull_request: {}
  push:
    branches: master

jobs:
  check-no-std-panic-conflict:
    name: Check no_std panic conflict
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: |
          cd tools/no-std-check
          make check-panic-conflict

  check-substrate:
    name: Check no_std substrate support
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
          override: true
      - run: |
          cd tools/no-std-check
          make check-substrate
