name: Test
on:
  pull_request:
    paths-ignore:
      - "docs/**"
  push:
    paths-ignore:
      - "docs/**"
    branches:
      - main
      - 'v*.*.*'
jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main'"

  default-features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test

  # TODO(shonfeder): remove duplication once GitHub addresses one of these
  #  - https://github.community/t/support-for-yaml-anchors/16128/15
  #  - https://github.community/t/reusing-sharing-inheriting-steps-between-jobs-declarations/16851/13
  #  - https://github.community/t/using-matrix-variable-in-docker-image-name/17296
  tendermint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test-all-features
          args: -p tendermint

  tendermint-rpc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test-all-features
          args: -p tendermint-rpc

  tendermint-proto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test-all-features
          args: -p tendermint-proto

  tendermint-light-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      # NOTE: We test with default features to make sure things work without "unstable".
      - uses: actions-rs/cargo@v1
        name: Test with default features
        with:
          command: test
          args: -p tendermint-light-client
      - uses: actions-rs/cargo@v1
        name: Test with all features
        with:
          command: test-all-features
          args: -p tendermint-light-client

  # From https://rustwasm.github.io/docs/wasm-bindgen/wasm-bindgen-test/continuous-integration.html#github-actions
  tendermint-light-client-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: wasm-pack test --headless --chrome ./light-client-js/
      - run: wasm-pack test --headless --firefox ./light-client-js/

  tendermint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test-all-features
          args: -p tendermint-test

  tendermint-testgen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test-all-features
          args: -p tendermint-testgen

  kvstore-integration-stable:
    runs-on: ubuntu-latest
    services:
      tendermint:
        image: informaldev/tendermint:0.34.21
        ports:
          - 26656:26656
          - 26657:26657
          - 26660:26660
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test-all-features
          args: --manifest-path tools/kvstore-test/Cargo.toml -- --nocapture
        env:
          RUST_LOG: debug

  nightly-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-09-18
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test-all-features
        env:
          RUSTFLAGS: '-Zinstrument-coverage'
          LLVM_PROFILE_FILE: '%p-%m.profraw'
      - name: Install grcov
        run: |
          rustup component add llvm-tools-preview
          curl -L https://github.com/mozilla/grcov/releases/download/v0.8.11/grcov-x86_64-unknown-linux-gnu.tar.bz2 | tar jxf -
      - name: Run grcov
        run: |
          ./grcov . --source-dir . --binary-path ./target/debug/ --output-type lcov --output-path ./lcov.info --branch --ignore-not-existing
      - name: Upload to Codecov
        run: |
          bash <(curl -s https://codecov.io/bash) -f ./lcov.info
