---
name: Test
on:
  pull_request:
    paths-ignore:
      - "docs/**"
  push:
    paths-ignore:
      - "docs/**"
    branches:
      - master
      - "v*.*.*"
jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master'"

  test-all:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      # warn when test takes more than 5s, kill after 10s
      RUST_TEST_TIME_UNIT: "5000,10000"
      RUST_TEST_TIME_INTEGRATION: "5000,10000"
      RUST_TEST_TIME_DOCTEST: "5000,10000"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deps
        with:
          toolchain: nightly

      - name: Test tenderdash-proto
        shell: bash
        timeout-minutes: 6
        run: cargo test --all-features -p tenderdash-proto -- -Zunstable-options --ensure-time

      - name: Test tenderdash-abci
        shell: bash
        timeout-minutes: 6

        env:
          RUSTFLAGS: "-Cinstrument-coverage"
          LLVM_PROFILE_FILE: "%p-%m.profraw"
        run: cargo test --all-features -p tenderdash-abci -- -Zunstable-options --ensure-time

      - name: Emit docker logs on error
        if: failure()
        shell: bash
        run: docker logs tenderdash > tenderdash.log 2>&1

      - name: Archive docker logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: tenderdash.log
          path: tenderdash.log

      - name: Install grcov
        run: |
          rustup component add llvm-tools-preview
          curl -L https://github.com/mozilla/grcov/releases/download/v0.8.13/grcov-x86_64-unknown-linux-gnu.tar.bz2 | tar jxf -

      - name: Run grcov
        run: |
          ./grcov . --source-dir . --binary-path ./target/debug/ --output-type lcov --output-path ./lcov.info --branch --ignore-not-existing
      - name: Upload to Codecov
        run: |
          bash <(curl -s https://codecov.io/bash) -f ./lcov.info
